services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend1
    networks:
      - my-app-network

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend2
    networks:
      - my-app-network

  backend3:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend3
    networks:
      - my-app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge