upstream auth_servers {
    server auth-service-1:3001 weight=2;
    server auth-service-2:3001 weight=1;
}

upstream product_servers {
    server product-service-1:3002;
    server product-service-2:3002;
}

upstream order_servers {
    server order-service-1:3003;
    server order-service-2:3003;
}

server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth_servers/;
    }

    location /api/products/ {
        proxy_pass http://product_servers/;
    }

    location /api/orders/ {
        proxy_pass http://order_servers/;
    }
}